### ISSUE TITLE
Explain how to find the station's ID

### ISSUE THREAD

**Issue by basnijholt** [Juvawa/HomeAssistant9292OvApiSensor#3]
I used
```
import http.client
import json

query = "Kratonlaan"
response = http.client.HTTPConnection("api.9292.nl", timeout=1)
response.request(
    "GET",
    f"/0.1/locations?lang=nl-NL&q={query}",
    headers={"cache-control": "no-cache", "accept": "application/json"},
)
result = response.getresponse().read().decode("utf-8")

json.loads(result)
```
to find the right names of the bus stops I am interested in.

Maybe we could add the above code somewhere?

**Comment by Juvawa** [comment]
Good idea, I could put this in a helper folder in this repo. So other people can use this as well.

**Comment by basnijholt** [comment]
Actually, I didn't notice the [Example response](http://api.9292.nl/0.1/locations?lang=nl-NL&q=amsterdam) links, which are much easier to parse!
