### ISSUE TITLE
Intergration not found

### ISSUE THREAD

**Issue by 07Sev** [Juvawa/HomeAssistant9292OvApiSensor#9]
For some reason, my home assistant isn't picking up on the integration. I have installed it through HACS and I verified that it basically does the same as putting the files into the correct folder. I've copied the example configuration provided and only removed the (required) and (optional) marks with all offset spaces.

Any idea on how to fix it?

```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:552
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 1:25:07 PM (1 occurrences)
Last logged: 1:25:07 PM

The system cannot restart because the configuration is not valid: Platform error sensor.dutch_public_transport_api - Integration 'dutch_public_transport_api' not found.
```

**Comment by metbril** [comment]
Could you please update HACS? We have issued a new release that fixes some errors.

https://github.com/Juvawa/HomeAssistant9292OvApiSensor/releases/tag/0.10.0

Please let us know if this fixes your error.

**Comment by DavidWeijzen** [comment]
It did. I don't get an error when I call the integration in the config.yaml file but the sensor isn't showing up yet.

**Comment by metbril** [comment]
I think this is due to #20.
